//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KillProofModule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KillProofModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name or KillProof.me-ID:.
        /// </summary>
        internal static string Account_Name_or_KillProof_me_ID_ {
            get {
                return ResourceManager.GetString("Account Name or KillProof.me-ID:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything.
        /// </summary>
        internal static string Everything {
            get {
                return ResourceManager.GetString("Everything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractal Titles.
        /// </summary>
        internal static string Fractal_Titles {
            get {
                return ResourceManager.GetString("Fractal Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID:.
        /// </summary>
        internal static string ID_ {
            get {
                return ResourceManager.GetString("ID:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill Proof Smart Ping Menu.
        /// </summary>
        internal static string Kill_Proof_Smart_Ping_Menu {
            get {
                return ResourceManager.GetString("Kill Proof Smart Ping Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Refresh:.
        /// </summary>
        internal static string Last_Refresh_ {
            get {
                return ResourceManager.GetString("Last Refresh:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ...
        /// </summary>
        internal static string Loading___ {
            get {
                return ResourceManager.GetString("Loading ..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profile for &quot;{0}&quot; found :(.
        /// </summary>
        internal static string No_profile_for___0___found___ {
            get {
                return ResourceManager.GetString("No profile for \"{0}\" found :(", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet registered :(.
        /// </summary>
        internal static string Not_yet_registered___ {
            get {
                return ResourceManager.GetString("Not yet registered :(", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, share www.killproof.me with this player and help expand our database..
        /// </summary>
        internal static string Please__share_www_killproof_me_with_this_player_and_help_expand_our_database_ {
            get {
                return ResourceManager.GetString("Please, share www.killproof.me with this player and help expand our database.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by www.killproof.me.
        /// </summary>
        internal static string Powered_by_www_killproof_me {
            get {
                return ResourceManager.GetString("Powered by www.killproof.me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile available.
        /// </summary>
        internal static string profile_available {
            get {
                return ResourceManager.GetString("profile available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Proofs.
        /// </summary>
        internal static string Progress_Proofs {
            get {
                return ResourceManager.GetString("Progress Proofs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick access to ping kill proofs..
        /// </summary>
        internal static string Quick_access_to_ping_kill_proofs_ {
            get {
                return ResourceManager.GetString("Quick access to ping kill proofs.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raid Titles.
        /// </summary>
        internal static string Raid_Titles {
            get {
                return ResourceManager.GetString("Raid Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random token from selected wing when pressing Send To Chat.
        ///Left-Click: Toggle
        ///Right-Click: Iterate wings.
        /// </summary>
        internal static string Random_token_from_selected_wing_when_pressing_Send_To_Chat__nLeft_Click__Toggle_nRight_Click__Iterate_wings {
            get {
                return ResourceManager.GetString("Random token from selected wing when pressing Send To Chat.\\nLeft-Click: Toggle\\n" +
                        "Right-Click: Iterate wings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent profiles:.
        /// </summary>
        internal static string Recent_profiles_ {
            get {
                return ResourceManager.GetString("Recent profiles:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh map to see your profile..
        /// </summary>
        internal static string Refresh_map_to_see_your_profile_ {
            get {
                return ResourceManager.GetString("Refresh map to see your profile.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove profiles of leavers automatically..
        /// </summary>
        internal static string Remove_leavers_automatically_ {
            get {
                return ResourceManager.GetString("Remove leavers automatically.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes profiles of players which are not in squad..
        /// </summary>
        internal static string Removes_profiles_of_players_which_are_not_in_squad_ {
            get {
                return ResourceManager.GetString("Removes profiles of players which are not in squad.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To Chat
        ///Left-Click: Only send code up to a stack&apos;s worth (250x).
        ///Right-Click: Send killproof.me total amount..
        /// </summary>
        internal static string Send_To_Chat_nLeft_Click__Only_send_code_up_to_a_stack_s_worth__250x____nRight_Click__Send_killproof_me_total_amount_ {
            get {
                return ResourceManager.GetString("Send To Chat\\nLeft-Click: Only send code up to a stack\'s worth (250x). \\nRight-Cl" +
                        "ick: Send killproof.me total amount.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Smart Ping Menu.
        /// </summary>
        internal static string Show_Smart_Ping_Menu {
            get {
                return ResourceManager.GetString("Show Smart Ping Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a menu on the top left corner of your screen which
        ///allows you to quickly access and ping your killproofs.
        ///Loads on map change..
        /// </summary>
        internal static string Shows_a_menu_on_the_top_left_corner_of_your_screen_which_allows_you_to_quickly_access_and_ping_your_killproofs_ {
            get {
                return ResourceManager.GetString("Shows a menu on the top left corner of your screen which allows you to quickly ac" +
                        "cess and ping your killproofs.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titles.
        /// </summary>
        internal static string Titles {
            get {
                return ResourceManager.GetString("Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens.
        /// </summary>
        internal static string Tokens {
            get {
                return ResourceManager.GetString("Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0} of {1} (killproof.me/{2}).
        /// </summary>
        internal static string Total___0__of__1___killproof_me__2__ {
            get {
                return ResourceManager.GetString("Total: {0} of {1} (killproof.me/{2})", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit www.killproof.me and allow us to record your KillProofs for you..
        /// </summary>
        internal static string Visit_www_killproof_me_and_allow_us_to_record_your_KillProofs_for_you_ {
            get {
                return ResourceManager.GetString("Visit www.killproof.me and allow us to record your KillProofs for you.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You started Blish HUD while Guild Wars 2 was already running..
        /// </summary>
        internal static string You_started_Blish_HUD_while_Guild_Wars_2_was_already_running_ {
            get {
                return ResourceManager.GetString("You started Blish HUD while Guild Wars 2 was already running.", resourceCulture);
            }
        }
    }
}
