//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KillProofModule.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KillProofModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A new version of the KillProof module was found: ähnelt.
        /// </summary>
        internal static string A_new_version_of_the_KillProof_module_was_found_ {
            get {
                return ResourceManager.GetString("A new version of the KillProof module was found:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account Name or KillProof.me-ID: ähnelt.
        /// </summary>
        internal static string Account_Name_or_KillProof_me_ID_ {
            get {
                return ResourceManager.GetString("Account Name or KillProof.me-ID:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Everything ähnelt.
        /// </summary>
        internal static string Everything {
            get {
                return ResourceManager.GetString("Everything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fractal Titles ähnelt.
        /// </summary>
        internal static string Fractal_Titles {
            get {
                return ResourceManager.GetString("Fractal Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID:  ähnelt.
        /// </summary>
        internal static string ID_ {
            get {
                return ResourceManager.GetString("ID:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kill Proof Smart Ping Menu ähnelt.
        /// </summary>
        internal static string Kill_Proof_Smart_Ping_Menu {
            get {
                return ResourceManager.GetString("Kill Proof Smart Ping Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KillProof ähnelt.
        /// </summary>
        internal static string KillProof {
            get {
                return ResourceManager.GetString("KillProof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Refresh: ähnelt.
        /// </summary>
        internal static string Last_Refresh_ {
            get {
                return ResourceManager.GetString("Last Refresh:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading .. ähnelt.
        /// </summary>
        internal static string Loading___ {
            get {
                return ResourceManager.GetString("Loading ..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No profile for &quot;{0}&quot; found :( ähnelt.
        /// </summary>
        internal static string No_profile_for___0___found___ {
            get {
                return ResourceManager.GetString("No profile for \"{0}\" found :(", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not yet registered :( ähnelt.
        /// </summary>
        internal static string Not_yet_registered___ {
            get {
                return ResourceManager.GetString("Not yet registered :(", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please, share www.killproof.me with this player and help expand our database. ähnelt.
        /// </summary>
        internal static string Please__share_www_killproof_me_with_this_player_and_help_expand_our_database_ {
            get {
                return ResourceManager.GetString("Please, share www.killproof.me with this player and help expand our database.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Powered by www.killproof.me ähnelt.
        /// </summary>
        internal static string Powered_by_www_killproof_me {
            get {
                return ResourceManager.GetString("Powered by www.killproof.me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile ähnelt.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die profile available ähnelt.
        /// </summary>
        internal static string profile_available {
            get {
                return ResourceManager.GetString("profile available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quick access to ping kill proofs. ähnelt.
        /// </summary>
        internal static string Quick_access_to_ping_kill_proofs_ {
            get {
                return ResourceManager.GetString("Quick access to ping kill proofs.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Raid Titles ähnelt.
        /// </summary>
        internal static string Raid_Titles {
            get {
                return ResourceManager.GetString("Raid Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Random token from selected wing when pressing Send To Chat.
        ///Left-Click: Toggle
        ///Right-Click: Iterate wings ähnelt.
        /// </summary>
        internal static string Random_token_from_selected_wing_when_pressing_Send_To_Chat__nLeft_Click__Toggle_nRight_Click__Iterate_wings {
            get {
                return ResourceManager.GetString("Random token from selected wing when pressing Send To Chat.\\nLeft-Click: Toggle\\n" +
                        "Right-Click: Iterate wings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recent profiles: ähnelt.
        /// </summary>
        internal static string Recent_profiles_ {
            get {
                return ResourceManager.GetString("Recent profiles:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh map to see your profile. ähnelt.
        /// </summary>
        internal static string Refresh_map_to_see_your_profile_ {
            get {
                return ResourceManager.GetString("Refresh map to see your profile.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send To Chat
        ///Left-Click: Only send code up to a stack&apos;s worth (250x).
        ///Right-Click: Send killproof.me total amount. ähnelt.
        /// </summary>
        internal static string Send_To_Chat_nLeft_Click__Only_send_code_up_to_a_stack_s_worth__250x____nRight_Click__Send_killproof_me_total_amount_ {
            get {
                return ResourceManager.GetString("Send To Chat\\nLeft-Click: Only send code up to a stack\'s worth (250x). \\nRight-Cl" +
                        "ick: Send killproof.me total amount.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Smart Ping Menu ähnelt.
        /// </summary>
        internal static string Show_Smart_Ping_Menu {
            get {
                return ResourceManager.GetString("Show Smart Ping Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shows a menu on the top left corner of your screen which allows you to quickly access and ping your killproofs. ähnelt.
        /// </summary>
        internal static string Shows_a_menu_on_the_top_left_corner_of_your_screen_which_allows_you_to_quickly_access_and_ping_your_killproofs_ {
            get {
                return ResourceManager.GetString("Shows a menu on the top left corner of your screen which allows you to quickly ac" +
                        "cess and ping your killproofs.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titles ähnelt.
        /// </summary>
        internal static string Titles {
            get {
                return ResourceManager.GetString("Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tokens ähnelt.
        /// </summary>
        internal static string Tokens {
            get {
                return ResourceManager.GetString("Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total: {0} of {1} (killproof.me/{2}) ähnelt.
        /// </summary>
        internal static string Total___0__of__1___killproof_me__2__ {
            get {
                return ResourceManager.GetString("Total: {0} of {1} (killproof.me/{2})", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update available! Visit killproof.me/addons ähnelt.
        /// </summary>
        internal static string Update_available__Visit_killproof_me_addons {
            get {
                return ResourceManager.GetString("Update available! Visit killproof.me/addons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visit www.killproof.me and allow us to record your KillProofs for you. ähnelt.
        /// </summary>
        internal static string Visit_www_killproof_me_and_allow_us_to_record_your_KillProofs_for_you_ {
            get {
                return ResourceManager.GetString("Visit www.killproof.me and allow us to record your KillProofs for you.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You started Blish HUD while Guild Wars 2 was already running. ähnelt.
        /// </summary>
        internal static string You_started_Blish_HUD_while_Guild_Wars_2_was_already_running_ {
            get {
                return ResourceManager.GetString("You started Blish HUD while Guild Wars 2 was already running.", resourceCulture);
            }
        }
    }
}
